"""Generate the browser-owned, signed prompt plans from the API prompt source."""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "api"))

from backend.ai.prompts.builder import canonical_prompt_contract  # noqa: E402
from backend.lens.languages import UI_LANGUAGES, normalize, _LENS_CASE_MAP  # noqa: E402

codes = sorted({normalize(str(item["code"])).lower() for item in UI_LANGUAGES})
plans = {code: canonical_prompt_contract(code, want_memo=False) for code in codes}
payload = json.dumps(plans, ensure_ascii=False, separators=(",", ":"))
target = ROOT / "src" / "generated" / "canonical-prompt-plans.js"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n"
    f"export const BUNDLED_CANONICAL_PROMPT_PLANS = Object.freeze({payload});\n",
    encoding="utf-8",
)

# Share code aliases with browser prompt lookup rather than duplicating tables.
(ROOT / "src" / "generated" / "language-code-aliases.js").write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n"
    + "const ALIASES = Object.freeze(" + json.dumps(_LENS_CASE_MAP, sort_keys=True) + ");\n"
    + "export function normalizeLanguageCode(value) {\n"
    + "  const raw = String(value || '').trim().toLowerCase().replaceAll('_', '-');\n"
    + "  return String(ALIASES[raw] || raw).toLowerCase();\n"
    + "}\n", encoding="utf-8",
)
