"""Generate the browser-owned, signed prompt plans from the API prompt source."""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "api"))

from backend.ai.prompts.builder import canonical_prompt_contract  # noqa: E402
from backend.lens.languages import UI_LANGUAGES, normalize, _LENS_CASE_MAP  # noqa: E402

codes = sorted({normalize(str(item["code"])).lower() for item in UI_LANGUAGES})
plans = {code: canonical_prompt_contract(code, want_memo=False) for code in codes}
payload = json.dumps(plans, ensure_ascii=False, separators=(",", ":"))
target = ROOT / "src" / "generated" / "canonical-prompt-plans.js"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n"
    f"export const BUNDLED_CANONICAL_PROMPT_PLANS = Object.freeze({payload});\n",
    encoding="utf-8",
)

# Share code aliases with browser prompt lookup rather than duplicating tables.
(ROOT / "src" / "generated" / "language-code-aliases.js").write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n"
    + "const ALIASES = Object.freeze(" + json.dumps(_LENS_CASE_MAP, sort_keys=True) + ");\n"
    + "export function normalizeLanguageCode(value) {\n"
    + "  const raw = String(value || '').trim().toLowerCase().replaceAll('_', '-');\n"
    + "  return String(ALIASES[raw] || raw).toLowerCase();\n"
    + "}\n", encoding="utf-8",
)

from backend.ai.prompts.source_context import SOURCE_CONTEXT_HEADER, MAX_CONTEXT_GROUPS, MAX_CONTEXT_UNITS, MAX_CONTEXT_CHARS
(ROOT / "src/generated/source-context-policy.js").write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n" +
    "\n".join("export const " + key + " = " + json.dumps(value, ensure_ascii=False) + ";"
        for key, value in {"SOURCE_CONTEXT_HEADER": SOURCE_CONTEXT_HEADER, "MAX_CONTEXT_GROUPS": MAX_CONTEXT_GROUPS,
            "MAX_CONTEXT_UNITS": MAX_CONTEXT_UNITS, "MAX_CONTEXT_CHARS": MAX_CONTEXT_CHARS}.items()) + "\n", encoding="utf-8")

from backend.ai.prompts.localization import TRANSLATOR_IDENTITY_BASE, TASK_GUIDANCE, STYLE_EXAMPLES, LOCALIZATION_POLICY_VERSION
(ROOT / "src/generated/localization-content.js").write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n" +
    "export const TRANSLATOR_IDENTITY_BASE = " + json.dumps(TRANSLATOR_IDENTITY_BASE, ensure_ascii=False) + ";\n" +
    "export const TASK_GUIDANCE = " + json.dumps(TASK_GUIDANCE, ensure_ascii=False) + ";\n" +
    "export const LOCALIZATION_POLICY_VERSION = " + json.dumps(LOCALIZATION_POLICY_VERSION) + ";\n" +
    "export const STYLE_EXAMPLES = " + json.dumps(STYLE_EXAMPLES, ensure_ascii=False) + ";\n",
    encoding="utf-8",
)

# This leaf is a declaration. Loading it by path avoids importing the API's
# provider composition root (and its server-only dependencies) in a browser build.
import runpy
OLLAMA_TRANSLATION_SAMPLING = runpy.run_path(
    str(ROOT / "api" / "backend" / "ai" / "providers" / "ollama_sampling.py")
)["OLLAMA_TRANSLATION_SAMPLING"]
(ROOT / "src/generated/ollama-sampling.js").write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n" +
    "export const OLLAMA_TRANSLATION_SAMPLING = Object.freeze(" +
    json.dumps(OLLAMA_TRANSLATION_SAMPLING, sort_keys=True) + ");\n", encoding="utf-8")

from backend.ai.prompts.instruction_packs import INSTRUCTION_PACKS
(ROOT / "src/generated/instruction-packs.js").write_text(
    "// Generated by scripts/generate-canonical-prompt-plan.py; do not edit.\n" +
    "export const INSTRUCTION_PACKS = " + json.dumps(INSTRUCTION_PACKS, ensure_ascii=False) + ";\n", encoding="utf-8")
